<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Features\Academic\Commands\ClassGroup\BulkDeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\BulkPatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\BulkUpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\CreateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\DeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\PatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\RestoreAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\ClassGroup\UpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\BulkDeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\BulkPatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\BulkUpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\CreateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\DeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\PatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\RestoreAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Class\UpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\BulkDeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\BulkPatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\BulkUpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\CreateAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\DeleteAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\PatchAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\RestoreAcademicYear\**" />
    <Compile Remove="Features\Academic\Commands\Section\UpdateAcademicYear\**" />
    <Compile Remove="Features\Academic\klk\**" />
    <Compile Remove="Features\Academic\Queries\ClassGroup\ExportAcademicYear\**" />
    <Compile Remove="Features\Academic\Queries\Class\ExportAcademicYear\**" />
    <Compile Remove="Features\Academic\Queries\Section\ExportAcademicYear\**" />
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\BulkDeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\BulkPatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\BulkUpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\CreateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\DeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\PatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\RestoreAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\ClassGroup\UpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\BulkDeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\BulkPatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\BulkUpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\CreateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\DeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\PatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\RestoreAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Class\UpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\BulkDeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\BulkPatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\BulkUpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\CreateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\DeleteAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\PatchAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\RestoreAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Commands\Section\UpdateAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\klk\**" />
    <EmbeddedResource Remove="Features\Academic\Queries\ClassGroup\ExportAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Queries\Class\ExportAcademicYear\**" />
    <EmbeddedResource Remove="Features\Academic\Queries\Section\ExportAcademicYear\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\BulkDeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\BulkPatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\BulkUpdateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\CreateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\DeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\PatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\RestoreAcademicYear\**" />
    <None Remove="Features\Academic\Commands\ClassGroup\UpdateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\BulkDeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\BulkPatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\BulkUpdateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\CreateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\DeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\PatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\RestoreAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Class\UpdateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\BulkDeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\BulkPatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\BulkUpdateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\CreateAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\DeleteAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\PatchAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\RestoreAcademicYear\**" />
    <None Remove="Features\Academic\Commands\Section\UpdateAcademicYear\**" />
    <None Remove="Features\Academic\klk\**" />
    <None Remove="Features\Academic\Queries\ClassGroup\ExportAcademicYear\**" />
    <None Remove="Features\Academic\Queries\Class\ExportAcademicYear\**" />
    <None Remove="Features\Academic\Queries\Section\ExportAcademicYear\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\SchoolERP.Domain\SchoolERP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Mappings\" />
    <Folder Include="Features\Authentication\Queries\" />
    <Folder Include="Features\Rbac\Queries\Assignment\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
